PUT http://localhost:4000/api/private/cart
Content-Type: application/json

{
    "idUser": "uUx3Rp3AJAaHC0WXZNRmEeCPhUW2",
    "products":[
        {"productId": "626ffee1967c63984a9bca2b", "quantity": 1},
        {"productId": "62701f13cdc206940ccc7514", "quantity": 1},
        {"productId": "62701ff6cdc206940ccc752c", "quantity": 3}],
    "amount": 100
}

###
PUT http://localhost:4000/api/private/emptyCart
Content-Type: application/json

{
    "idUser": "62671fb086718c3f6e6214ac",
    "idOrder":"626721020fd4ea9eff96f1ea"
}