PUT http://localhost:4000/api/private/cart/62637ff66cc38964e19c79db
Content-Type: application/json

{
    "products":[
        {"productId":"6262f1843d7b11c0d34bdd10", "quantity": 1},
        {"productId":"625e19889e864286771b0ba4", "quantity": 1}],
    "amount": 2800
}

###
PUT http://localhost:4000/api/private/emptyCart/62637ff66cc38964e19c79db