PUT http://localhost:4000/api/private/cart
Content-Type: application/json

{
    "idUser": "kDJhV2C1H4ZwVaqjzwB8Hb2Jgnt2",
    "products":[{"productId": "62700faf67dcc825f9109ada", "quantity": 2},
    {"productId": "627048a54ab75f392ad78c31", "quantity": 2}],
    "amount": 100
}

###
PUT http://localhost:4000/api/private/emptyCart
Content-Type: application/json

{
    "idUser": "62671fb086718c3f6e6214ac",
    "idOrder":"626721020fd4ea9eff96f1ea"
}