POST http://localhost:4000/api/private/addOrder
Content-Type: application/json

{
    "idUser": "kDJhV2C1H4ZwVaqjzwB8Hb2Jgnt2"
}

###
GET http://localhost:4000/api/private/orderSellers/62671fb086718c3f6e6214ac

###
PUT http://localhost:4000/api/private/updateOrder
Content-Type: application/json

{
    "idOrder": "62681023ec90d13d5f9246d2",
    "status": "Approved"
}