POST http://localhost:4000/api/private/addOrder
Content-Type: application/json

{
    "idUser": "uUx3Rp3AJAaHC0WXZNRmEeCPhUW2"
}

###
GET http://localhost:4000/api/private/orderSellers/62671fb086718c3f6e6214ac

###
PUT http://localhost:4000/api/private/updateOrder
Content-Type: application/json

{
    "idOrder": "62681023ec90d13d5f9246d2",
    "status": "Approved"
}

###
PUT http://localhost:4000/api/private/updateDispatches
Content-Type: application/json

{
    "idUser": "1j6PbhrcMHRPBpwRTHIgtFhQAuF2",
    "idOrder": "6271b1056af4d7a75e7d3453"
}