### Post a new product
POST http://localhost:4000/api/private/product
Content-Type: application/json

{
    "name": "Sandiaas",
    "description": "blablablasx5",
    "image": "imagensensita",
    "stock": 3,
    "discount": 0,
    "category": ["6255aa9a351a9ea80e5af836","6255d99ba2e6d5a6702ac752"],
    "price": 8000,
    "userId": "62573b9bf94ccd0d5b502f1f"
}

### Update a product
PUT http://localhost:4000/api/private/product/:id
Content-Type: application/json

{
    "name": "manzanitaNueva",
    "description": "blablablasx3",
    "image": "imagensita",
    "stock": 2,
    "discount": 0,
    "price": 8000
}