### Post a new product
POST http://localhost:4000/api/private/product
Content-Type: application/json

{
    "name": "San Valentin",
    "description": "blablablasx5",
    "image": "",
    "stock": 3,
    "category": ["6255aa9a351a9ea80e5af836","6255d99ba2e6d5a6702ac752"],
    "price": 8000,
    "userId": "6256d1c7b4ceca231cfff253"
}

### Update a product
PUT http://localhost:4000/api/private/product/62607ae3bac751b2acb6dc4f
Content-Type: application/json

{
    "name": "Pan de pancho",
    "description": "Pan para tus panchos",
    "image": "http://res.cloudinary.com/markets-center/image/upload/v1650490083/qtivsvgflix9piqbzxkc.jpg",
    "stock": 100,
    "category": [
      {
        "_id": "625e18528435e20ed2b70f6c",
        "name": "Cereales y derivados"
      }
    ],
    "price": 200
}