### Get todos los usuarios
GET http://localhost:4000/api/private/users

### post un usuario nuevo
POST http://localhost:4000/api/private/users/add
Content-Type: application/json

{
    "name": "Menganitoo",
    "userId": "ieo0w5utv89w4menganito21u",
    "email": "menganito2@test.com",
    "isSeller": true,
    "phone": 1234567840,
    "IdDocument": 12345578,
    "dateofBirth": "24/10/87",
    "address": "cualquier casa"
}

### actualiza un usuario
PUT http://localhost:4000/api/private/users/update/
Content-Type: application/json

{
    "name": "Claudia Neme",
    "picture": "fotito",
    "user_id": "ieo0w5utv89w4uyt",
    "email": "focaloca@test.com",
    "isSeller": false,
    "phone": 1234567890,
    "IdDocument": 12345678,
    "dateofBirth": "25/10/87",
    "address": "cualquier casa",
    "isAdmin": true
}

### get de todos los vendedores
GET http://localhost:4000/api/private/users/sellers

###
GET http://localhost:4000/api/private/users/history/62671fb086718c3f6e6214ac