
### Getting all or query products(name=Productito)
GET http://localhost:5000/api/public/products

### Getting product by his id
GET http://localhost:5000/api/public/product/6254d5893905e29a56b6fcf8

### Delete a product by his id
DELETE http://localhost:5000/api/public/product/6255d9c3a2e6d5a6702ac756